language: cpp

os: linux
sudo: required
dist: trusty

compiler:
    - gcc

addons:
    apt:
        sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.9
            - g++-4.9
            - python3.5
            - python3.5-dev
            - mesa-common-dev
            - libglu1-mesa-dev

before_install:
    - sudo add-apt-repository -y ppa:beineri/opt-qt56-trusty
    - sudo apt-get -qq update
    - wget https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.sh
    - sudo mkdir -p /opt/cmake

install:
    - sudo apt-get install -y qt-latest
    - sudo bash cmake-3.5.2-Linux-x86_64.sh --prefix=/opt/cmake --skip-license

before_script:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
    # Qt 5.6
    - export PATH=/opt/cmake/bin:/opt/qt56/bin:$PATH
    - bash /opt/qt56/bin/qt56-env.sh
    # Build directory
    - mkdir ../build-stoiridh-controls
    - cd ../build-stoiridh-controls
    - export PATH=$HOME/viprip/build-stoiridh-controls/install-root/bin:$PATH

script:
    # CMake build
    - cmake -G"Unix Makefiles" ../Stoiridh.Controls
    - make
    - ctest -E "^Stoiridh.Controls$"
    
    - qbs clean --all-artifacts -d ../build-stoiridh-controls
    - qbs build -d ../build-stoiridh-controls StoiridhUtils.Project.productName:StoiridhControls
    - qbs install -d ../build-stoiridh-controls
    # TODO Merge the following autotests with the command below when a new version of Stoiridh Qbs
    #      Configuration (1.1.0) shall release.
    # - qbs run -p "autotest-runner" -d ../build-stoiridh-controls

    # Stoiridh.Controls.Templates autotests
    - qbs run -p "[Core] Exception Autotest" -d ../build-stoiridh-controls
    - qbs run -p "[Core] ExceptionHandler Autotest" -d ../build-stoiridh-controls
    - qbs run -p "[Core] NullPointerException Autotest" -d ../build-stoiridh-controls
    - qbs run -p "[Stoiridh.Controls.Templates] Control Autotest" -d ../build-stoiridh-controls
    - qbs run -p "[Stoiridh.Controls.Templates] Padding Autotest" -d ../build-stoiridh-controls
    # Stoiridh.Controls.Templates autotests (internal)
    - qbs run -p "[Internal] AbstractStyleDispatcher Autotest" -d ../build-stoiridh-controls
    # - qbs run -p "[Internal] Style Autotest" -d ../build-stoiridh-controls
    # - qbs run -p "[Internal] StyleDispatcher Autotest" -d ../build-stoiridh-controls
    # - qbs run -p "[Internal] StyleFactory Autotest" -d ../build-stoiridh-controls
    # - qbs run -p "[Internal] StyleFactoryHelper Autotest" -d ../build-stoiridh-controls
    - qbs run -p "[Internal] StylePropertyChanges Autotest" -d ../build-stoiridh-controls
    - qbs run -p "[Internal] StylePropertyExpression Autotest" -d ../build-stoiridh-controls
    # - qbs run -p "[Internal] StyleState Autotest" -d ../build-stoiridh-controls
    - qbs run -p "[Internal] StyleStateController Autotest" -d ../build-stoiridh-controls
    - qbs run -p "[Internal] StyleStateOperation Autotest" -d ../build-stoiridh-controls
